name: Hygiene
on:
  push:
    branches:
      - main
  pull_request:
    types:
      - opened
      - reopened
      - synchronize
      - ready_for_review
  workflow_dispatch:

env:
  MSRV: 1.85.0

permissions: {}

jobs:
  code-hygiene:
    name: Code Hygiene
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2
        with:
          persist-credentials: false

      - name: Install Rust
        uses: actions-rust-lang/setup-rust-toolchain@150fca883cd4034361b621bd4e6a9d34e5143606 # v1.15.4
        with:
          components: rustfmt, clippy
          toolchain: ${{ env.MSRV }}

      - name: Rustfmt
        run: cargo fmt --all --check

      - name: Clippy
        run: cargo clippy --all-features

      - name: Check for typos
        uses: crate-ci/typos@02ea592e44b3a53c302f697cddca7641cd051c3d # v1.45.0

  tests:
    name: Tests
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2
        with:
          persist-credentials: false

      - name: Install Rust
        uses: actions-rust-lang/setup-rust-toolchain@150fca883cd4034361b621bd4e6a9d34e5143606 # v1.15.4
        with:
          components: rust-src # https://github.com/dtolnay/trybuild?tab=readme-ov-file#troubleshooting
          toolchain: ${{ env.MSRV }}

      - name: "Tests (features: default)"
        run: cargo test --no-fail-fast

      - name: "Tests (features: none)"
        run: cargo test --no-default-features --no-fail-fast

      - name: "Tests (features: all)"
        run: cargo test --all-features --no-fail-fast

  zizmor:
    name: Zizmor
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2
        with:
          persist-credentials: false

      - name: Install Zizmor
        uses: taiki-e/install-action@0cccd59f03b32c54f0db097c518c320bfc8c73b3 # v2.71.1
        with:
          tool: zizmor

      - name: Zizmor
        run: zizmor .
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
